[nfs]
172.31.0.176 ansible_ssh_pass=vagrant ansible_ssh_user=vagrant

[webservers]
172.31.12.103 ansible_ssh_pass=vagrant ansible_ssh_user=vagrant
172.31.5.216 ansible_ssh_pass=vagrant ansible_ssh_user=vagrant

[db]
172.31.3.53 ansible_ssh_pass=vagrant ansible_ssh_user=vagrant

[lb]
172.31.4.254 ansible_ssh_user='ubuntu'

